 - name: add ssh key for devin
   authorized_key:
     user: simone
     key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF3Qg0+ic+wT+aK9oLXf/fuE52xSx3cH+e0/tcR0czm8 ansible"
 - name: generate sshd_config file from template
   tags: ssh
   template:
     src: "{{ ssh_template_file }}"
     dest: /etc/ssh/sshd_config
     owner: root
     group: root
     mode: 0644
   notify: restart_sshd

